name: ds_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - polars
      - plotly
      - xgboost
      - lightgbm
      - catboost
      - transformers
      - datasets
      - nltk
